# file .circleci/config.yml
defaults: &defaults
  environment:
    CIRCLE_ARTIFACTS: /tmp/circleci-artifacts
    CIRCLE_TEST_REPORTS: /tmp/circleci-test-results
    DOCKER_REGISTRY: 9999999999999.dkr.ecr.eu-west-1.amazonaws.com
    DOCKER_TAG_NAME: <NAMESPACE>/<SERVICENAME>  # e.g. motione/motione-groups or myservice
  docker:
    - image: strindhaug/zep-k8s-build:0.0.1
  working_directory: ~/<NAMESPACE>/<SERVICENAME> # e.g. ~/motione/motione-groups or ~/myservice

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Install common ci-scripts
          command: |
            git clone -b 'v0.2.0' --single-branch --depth 1 https://github.com/zeppelin-no/ci-scripts.git
      - run:
          name: 'Setup'
          command: ./ci-scripts/setup.sh
      - run:
          name: 'Build'
          command: ./ci-scripts/build.sh
      - run:
          name: 'Deploy'
          command: ./ci-scripts/deploy.sh <NAMESPACE>
      - run:
          name: 'Delete pods to restart server'
          command: kubectl delete pods -l app=<APPNAME> --namespace=<NAMESPACE>

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
