defaults: &defaults
  environment:
    CIRCLE_ARTIFACTS: /tmp/circleci-artifacts
    CIRCLE_TEST_REPORTS: /tmp/circleci-test-results
    DOCKER_REGISTRY: 259266063917.dkr.ecr.eu-west-1.amazonaws.com
    DOCKER_TAG_NAME: <SERVICENAME>  # e.g. myservice
    K8_APP_NAME: <APPNAME>  # name of the kubernetes app e.g. myapp
    CI_SCRIPTS_TAG: ci2-v0.2.3 # release tag
    # CI_SCRIPTS_TAG: feature/circle-ci-2.0 # development branch
  docker:
    - image: strindhaug/zep-k8s-build:0.0.1-kubectl-v1.8.7
  working_directory: ~/zeppelin-no/workdir

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      # Restore the dependency cache
      # - restore_cache:
      #     keys:
      #     # This branch if available
      #     - v1-dep-{{ .Branch }}-
      #     # Default branch if not
      #     - v1-dep-master-
      #     # Any branch if there are none on the default branch - this should be unnecessary if you have your default branch configured correctly
      #     - v1-dep-
      - run:
          name: Install common ci-scripts
          command: git clone -b "${CI_SCRIPTS_TAG}" --single-branch --depth 1 https://github.com/zeppelin-no/ci-scripts.git
      - run:
          name: 'Authenticate'
          command: ./ci-scripts/auth.sh prod
      - run:
          name: 'Build'
          command: ./ci-scripts/build.sh
      - run:
          name: 'Push'
          command: ./ci-scripts/push.sh
      # - save_cache:
      #     key: v1-dep-{{ .Branch }}-{{ epoch }}
      #     paths:
      #     - ~/zeppelin-no/workdir/docker


  deploy:
    <<: *defaults
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Install common ci-scripts
          command: git clone -b "${CI_SCRIPTS_TAG}" --single-branch --depth 1 https://github.com/zeppelin-no/ci-scripts.git
      - run:
          name: 'Authenticate'
          command: ./ci-scripts/auth.sh prod
      - run:
          name: 'Apply'
          command: ./ci-scripts/apply.sh prod
      - run:
          name: 'Delete pods to restart server'
          command: kubectl delete pods -l app="${K8_APP_NAME}" --namespace=prod

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - master
