version: 2
jobs:
  test:
    docker:
      # - image: alpine:3.7
      # - image: docker:18.03-git
      - image: strindhaug/zep-k8s-build:0.0.1-kubectl-v1.8.7
    steps:
      - checkout
      - run: ./ensure-tools.sh
      - run: kubectl version --client
      - run: ./k8s/authenticate.sh
      - run: ./ecr/authenticate.sh
      - run: kubectl get pods --all-namespaces
      - run: ./k8s/authenticate.sh dev
workflows:
  version: 2
  build_and_test:
    jobs:
      - test
