version: 2
jobs:
  test:
    docker:
      # - image: alpine:3.7
      - image: docker:18.03-git
    steps:
      - checkout
      - run: /root/project/k8s/ensure-kubectl.sh
      - run: kubectl version --client
      - run: /root/project/k8s/authenticate.sh
      # - run: /root/project/ecr/authenticate.sh
      - run: kubectl get pods --all-namespaces
      - run: /root/project/k8s/authenticate.sh dev
workflows:
  version: 2
  build_and_test:
    jobs:
      - test
