version: 2
jobs:
  test:
    # environment:
    #   K8S_ENDPOINT: todo endpoint
    #   K8S_USERNAME: todo username
    #   K8S_PASSWORD: todo password
    docker:
      # - image: buildpack-deps:trusty
      # - image: circleci/build-image:ubuntu-14.04-XXL-upstart-1189-5614f37
      - image: alpine:3.7

    steps:
      - checkout
      # - run: pwd
      # - run: ls
      # - run: echo $PATH
      - run: /root/project/run_tests.sh
workflows:
  version: 2
  build_and_test:
    jobs:
      - test
